language: android
jdk: openjdk8

android:
  components:
    - tools
    - build-tools-29.0.2
    - android-29
    - extra-android-m2repository
    - extra-android-support

notifications:
  email: false

before_install:
 - chmod +x gradlew

script: ./gradlew clean
